version: '3.8'
services:
  rtl-tcp:
    image: legacycode/rtlsdr
    container_name: rtl-tcp
    command: rtl_tcp -a 0.0.0.0 -p 1234
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "1234:1234"
    restart: unless-stopped

  rtl-mux:
    build:
      context: ./rtl-mux
    container_name: rtl-mux
    depends_on:
      - rtl-tcp
    ports:
      - "1235:1235"
    restart: unless-stopped
networks:
  sdr:
    driver: bridge